#!/usr/bin/env python3
"""
8-day sequential LSEG ingestion validation harness.

Produces:
  BENCHMARK_REPORT.md     — per-file and per-day timing
  DAILY_CHANGES_REPORT.md — insert/update/unchanged counts and table row deltas per day
  INGESTION_SUMMARY.md    — stability notes: exceptions, retries, failed files, pool
  COLUMN_CHANGES_MATRIX.md— generated by generate_change_matrix.py via system versioning
"""

import requests
import time
import json
import sys
import subprocess
from datetime import datetime

try:
    import pymysql
    import pymysql.cursors
except ImportError:
    print("ERROR: pymysql not installed. Run: pip install pymysql")
    sys.exit(1)

DATES = ["20260425", "20260426", "20260427", "20260428", "20260429", "20260430", "20260501", "20260502"]
BASE_URL = "http://localhost:8080/api"
HEALTH_URL = "http://localhost:8080/actuator/health"

DB_CONFIG = {
    "host": "127.0.0.1",
    "port": 3306,
    "user": "root",
    "password": "rootpw",
    "database": "lseg",
    "connect_timeout": 10,
}


# ─── DB helpers ───────────────────────────────────────────────────────────────

def get_db_conn():
    return pymysql.connect(**DB_CONFIG)


def get_table_counts():
    conn = get_db_conn()
    counts = {}
    with conn.cursor() as cur:
        for tbl in ("lseg_orgs", "lseg_assets", "lseg_quotes", "lseg_quotes_delisted", "lseg_pricing", "lseg_dss_bonds"):
            try:
                cur.execute(f"SELECT COUNT(*) FROM {tbl}")
                counts[tbl] = cur.fetchone()[0]
            except Exception:
                counts[tbl] = None
    conn.close()
    return counts


def get_audit_totals_for_job(job_id):
    conn = get_db_conn()
    with conn.cursor(pymysql.cursors.DictCursor) as cur:
        cur.execute("""
            SELECT
                SUM(parsed_rows)    AS total_parsed,
                SUM(inserted_rows)  AS total_inserted,
                SUM(updated_rows)   AS total_updated,
                SUM(unchanged_rows) AS total_unchanged,
                SUM(skipped_rows)   AS total_skipped,
                SUM(ins_count)      AS total_ins,
                SUM(upd_count)      AS total_upd,
                SUM(del_count)      AS total_del,
                COUNT(*)            AS file_count,
                SUM(CASE WHEN status='SUCCESS' THEN 1 ELSE 0 END) AS success_files,
                SUM(CASE WHEN status='FAILED'  THEN 1 ELSE 0 END) AS failed_files,
                SUM(CASE WHEN status LIKE 'SKIPPED%%' THEN 1 ELSE 0 END) AS skipped_files
            FROM lseg_file_audit
            WHERE business_date = (SELECT business_date FROM lseg_jobs WHERE id = %s)
              AND status NOT IN ('STARTED')
        """, (job_id,))
        row = cur.fetchone()
    conn.close()
    return row or {}


def get_file_details_for_job(job_id):
    conn = get_db_conn()
    with conn.cursor(pymysql.cursors.DictCursor) as cur:
        cur.execute("""
            SELECT
                file_name, dataset, target_table, kind, seq,
                declared_rows, parsed_rows, inserted_rows, updated_rows,
                unchanged_rows, skipped_rows, ins_count, upd_count, del_count,
                status, error_message,
                TIMESTAMPDIFF(SECOND, started_at, finished_at) AS duration_sec,
                started_at, finished_at
            FROM lseg_file_audit
            WHERE business_date = (SELECT business_date FROM lseg_jobs WHERE id = %s)
            ORDER BY target_table, kind, seq, started_at
        """, (job_id,))
        rows = cur.fetchall()
    conn.close()
    return rows


def get_failed_files_for_job(job_id):
    conn = get_db_conn()
    with conn.cursor(pymysql.cursors.DictCursor) as cur:
        cur.execute("""
            SELECT file_name, target_table, kind, status, error_message
            FROM lseg_file_audit
            WHERE business_date = (SELECT business_date FROM lseg_jobs WHERE id = %s)
              AND status IN ('FAILED', 'SKIPPED_SANITY')
            ORDER BY status, file_name
        """, (job_id,))
        rows = cur.fetchall()
    conn.close()
    return rows


def find_completed_job_for_date(date):
    """Return the most recent COMPLETED MAIN job_id for a given business date, or None.
    Scoped to MAIN so the isolated DELISTED job is never reused as the main run."""
    conn = get_db_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT id FROM lseg_jobs WHERE business_date=%s AND status='COMPLETED' "
                "AND job_type='MAIN' ORDER BY id DESC LIMIT 1",
                (date,)
            )
            row = cur.fetchone()
            return row[0] if row else None
    except Exception:
        return None
    finally:
        conn.close()


def get_job_wall_time(job_id):
    """Return wall time in seconds for a job (started_at to finished_at)."""
    conn = get_db_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT TIMESTAMPDIFF(SECOND, started_at, finished_at) FROM lseg_jobs WHERE id=%s",
                (job_id,)
            )
            row = cur.fetchone()
            return row[0] if row and row[0] else 0
    except Exception:
        return 0
    finally:
        conn.close()


def get_pool_status():
    """Read HikariCP pool stats from Micrometer metrics endpoint."""
    try:
        r = requests.get("http://localhost:8080/actuator/metrics/hikaricp.connections.active", timeout=5)
        if r.status_code == 200:
            data = r.json()
            active = data.get("measurements", [{}])[0].get("value", "?")
            return f"active={active}"
    except Exception:
        pass
    return "unavailable"


# ─── Job control ──────────────────────────────────────────────────────────────

def trigger_job(date, job_type="MAIN"):
    input_dir = f"/data/{date}"
    url = f"{BASE_URL}/jobs/trigger"
    r = requests.post(url, params={"businessDate": date, "inputDir": input_dir, "jobType": job_type}, timeout=10)
    r.raise_for_status()
    body = r.json()
    return body["jobId"]


def run_delisted_job(date):
    """Trigger and wait for the isolated DELISTED job that ingests INTDELISTED files
    into lseg_quotes_delisted. Serializes behind the cluster lock after the MAIN job."""
    print(f"  Triggering DELISTED job ...", end=" ")
    try:
        job_id = trigger_job(date, job_type="DELISTED")
        print(f"job_id={job_id}")
    except Exception as e:
        print(f"\n  DELISTED TRIGGER FAILED for {date}: {e}")
        return None, "TRIGGER_FAILED"
    print(f"  Waiting for DELISTED completion ...", end=" ", flush=True)
    status = wait_for_job(job_id)
    print(status)
    return job_id, status


def wait_for_job(job_id, poll_interval=5, timeout_minutes=60):
    deadline = time.time() + timeout_minutes * 60
    while time.time() < deadline:
        try:
            r = requests.get(f"{BASE_URL}/jobs/status", params={"jobId": job_id}, timeout=10)
            r.raise_for_status()
            status = r.json()["status"]
            if status in ("COMPLETED", "FAILED", "STOPPED"):
                return status
        except Exception as e:
            print(f"  [warn] poll failed: {e}")
        time.sleep(poll_interval)
    return "TIMEOUT"


# ─── Smoke test ───────────────────────────────────────────────────────────────

def smoke_test():
    print("=" * 60)
    print("SMOKE TEST")
    print("=" * 60)

    # 1. Health check
    print("  [1/4] Checking /actuator/health ...", end=" ")
    for attempt in range(30):
        try:
            r = requests.get(HEALTH_URL, timeout=5)
            if r.status_code == 200 and r.json().get("status") == "UP":
                print("UP")
                break
        except Exception:
            pass
        if attempt == 29:
            print("FAILED — application did not come up within 150s")
            sys.exit(1)
        time.sleep(5)

    # 2. DB connectivity
    print("  [2/4] Checking DB connectivity ...", end=" ")
    try:
        conn = get_db_conn()
        with conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM lseg_jobs")
        conn.close()
        print("OK")
    except Exception as e:
        print(f"FAILED: {e}")
        sys.exit(1)

    # 3. Pool size verification
    print("  [3/4] Connection pool config ...", end=" ")
    try:
        r = requests.get("http://localhost:8080/actuator/metrics/hikaricp.connections.max", timeout=5)
        if r.status_code == 200:
            max_pool = r.json()["measurements"][0]["value"]
            print(f"maxPoolSize={int(max_pool)}", end="")
            if max_pool < 20:
                print(f" — WARNING: pool may be too small for parallel ingestion (need ~22)")
            else:
                print(" — OK")
        else:
            print(f"HTTP {r.status_code}")
    except Exception as e:
        print(f"skipped ({e})")

    # 4. Trigger day-1 canary (skip if already completed)
    print("  [4/4] Trigger test ...", end=" ")
    existing = find_completed_job_for_date(DATES[0])
    if existing:
        print(f"day-1 already completed (job_id={existing}), skipping re-trigger")
        return None
    try:
        r = requests.post(f"{BASE_URL}/jobs/trigger",
                          params={"businessDate": DATES[0], "inputDir": f"/data/{DATES[0]}"},
                          timeout=10)
        if r.status_code == 200:
            jid = r.json()["jobId"]
            print(f"queued job_id={jid}")
            return jid
        else:
            print(f"HTTP {r.status_code}: {r.text}")
            sys.exit(1)
    except Exception as e:
        print(f"FAILED: {e}")
        sys.exit(1)


# ─── Main run ─────────────────────────────────────────────────────────────────

def run():
    print(f"\nLSEG 8-Day Ingestion Validation — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Dates: {DATES[0]} → {DATES[-1]}\n")

    # Smoke test verifies health/pool; may reuse existing day-1 job if already completed
    first_job_id = smoke_test()
    print()

    all_results = {}
    prev_counts = get_table_counts()
    stability_notes = []

    for i, date in enumerate(DATES):
        print(f"{'='*60}")
        print(f"DAY {i+1}/8 — {date}")
        print(f"{'='*60}")

        day_start = time.time()

        # Check if this date was already completed (e.g. from smoke test run)
        existing_job = find_completed_job_for_date(date)
        if existing_job:
            job_id = existing_job
            wall_sec = get_job_wall_time(job_id)
            print(f"  Reusing already-completed job_id={job_id} (wall={wall_sec}s)")
            final_status = "COMPLETED"
        elif i == 0 and first_job_id:
            job_id = first_job_id
            print(f"  Using smoke-test job_id={job_id}")
            print(f"  Waiting for completion ...", end=" ", flush=True)
            final_status = wait_for_job(job_id)
            wall_sec = time.time() - day_start
            print(f"{final_status} ({wall_sec:.0f}s)")
        else:
            print(f"  Triggering job ...", end=" ")
            try:
                job_id = trigger_job(date)
                print(f"job_id={job_id}")
            except Exception as e:
                msg = f"TRIGGER FAILED for {date}: {e}"
                print(f"\n  {msg}")
                stability_notes.append(msg)
                all_results[date] = {"status": "TRIGGER_FAILED", "job_id": None, "wall_sec": 0,
                                     "totals": {}, "files": [], "failed_files": [], "counts": {}}
                continue

            print(f"  Waiting for completion ...", end=" ", flush=True)
            final_status = wait_for_job(job_id)
            wall_sec = time.time() - day_start
            print(f"{final_status} ({wall_sec:.0f}s)")

        status = final_status

        if status != "COMPLETED":
            msg = f"Job {job_id} for {date} ended with status={status}"
            stability_notes.append(msg)

        # Isolated delisted job: ingests INTDELISTED files into lseg_quotes_delisted.
        # Runs after the MAIN job; the cluster lock serializes the two.
        delisted_job_id, delisted_status = run_delisted_job(date)
        if delisted_status != "COMPLETED":
            stability_notes.append(f"DELISTED job for {date} ended with status={delisted_status}")

        totals = get_audit_totals_for_job(job_id)
        files = get_file_details_for_job(job_id)
        failed_files = get_failed_files_for_job(job_id)
        curr_counts = get_table_counts()

        if failed_files:
            for ff in failed_files:
                msg = f"[{date}] {ff['status']} {ff['file_name']}: {(ff['error_message'] or '')[:120]}"
                stability_notes.append(msg)
            print(f"  WARNING: {len(failed_files)} file(s) failed/skipped — see stability notes")

        # Summarise timing per target
        target_stats = {}
        for row in files:
            t = row["target_table"] or "unknown"
            if t not in target_stats:
                target_stats[t] = {"files": 0, "parsed": 0, "inserted": 0, "updated": 0,
                                   "unchanged": 0, "max_sec": 0, "total_sec": 0}
            s = target_stats[t]
            s["files"] += 1
            s["parsed"] += row["parsed_rows"] or 0
            s["inserted"] += row["inserted_rows"] or 0
            s["updated"] += row["updated_rows"] or 0
            s["unchanged"] += row["unchanged_rows"] or 0
            dur = row["duration_sec"] or 0
            s["max_sec"] = max(s["max_sec"], dur)
            s["total_sec"] += dur

        for t, s in sorted(target_stats.items()):
            print(f"    {t:12s}: files={s['files']:4d}  parsed={s['parsed']:8,d}  "
                  f"ins={s['inserted']:7,d}  upd={s['updated']:7,d}  max={s['max_sec']}s")

        all_results[date] = {
            "status": status,
            "job_id": job_id,
            "wall_sec": wall_sec,
            "totals": totals,
            "files": files,
            "failed_files": failed_files,
            "target_stats": target_stats,
            "prev_counts": prev_counts,
            "curr_counts": curr_counts,
        }
        prev_counts = curr_counts
        print()

    # ── Report generation ──────────────────────────────────────────────────────
    print("Generating reports ...")
    _write_benchmark(all_results)
    _write_daily_changes(all_results)
    _write_stability(all_results, stability_notes)

    print("Running column-level change matrix (may be slow) ...")
    try:
        result = subprocess.run(
            [sys.executable, "scripts/generate_change_matrix.py"],
            capture_output=True, text=True, timeout=600,
            cwd="/Users/sa/Downloads/LSEG/lseg-ingest"
        )
        if result.returncode == 0:
            print("  COLUMN_CHANGES_MATRIX.md written")
        else:
            print(f"  change_matrix failed: {result.stderr[:200]}")
    except Exception as e:
        print(f"  change_matrix skipped: {e}")

    print("\nAll reports written:")
    print("  BENCHMARK_REPORT.md")
    print("  DAILY_CHANGES_REPORT.md")
    print("  INGESTION_SUMMARY.md")
    print("  COLUMN_CHANGES_MATRIX.md")


# ─── Report writers ───────────────────────────────────────────────────────────

def _write_benchmark(all_results):
    lines = [
        "# LSEG Ingestion — Benchmark Report",
        f"\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "\n## Per-Day Summary\n",
        "| Date | Status | Wall Time (s) | Files | Parsed | Inserted | Updated | Unchanged | Failed Files |",
        "| ---- | ------ | ------------- | ----- | ------ | -------- | ------- | --------- | ------------ |",
    ]
    for date, r in all_results.items():
        t = r.get("totals", {})
        lines.append(
            f"| {date} | {r['status']} | {r['wall_sec']:.0f} "
            f"| {t.get('file_count') or 0} "
            f"| {(t.get('total_parsed') or 0):,} "
            f"| {(t.get('total_inserted') or 0):,} "
            f"| {(t.get('total_updated') or 0):,} "
            f"| {(t.get('total_unchanged') or 0):,} "
            f"| {t.get('failed_files') or 0} |"
        )

    for date, r in all_results.items():
        lines += [
            f"\n## {date} (job_id={r['job_id']}, wall={r['wall_sec']:.0f}s, status={r['status']})",
            "",
            "### Per-Target Breakdown",
            "| Target | Files | Parsed | Inserted | Updated | Unchanged | Max File (s) |",
            "| ------ | ----- | ------ | -------- | ------- | --------- | ------------ |",
        ]
        for tgt, s in sorted(r.get("target_stats", {}).items()):
            lines.append(
                f"| {tgt} | {s['files']} | {s['parsed']:,} | {s['inserted']:,} "
                f"| {s['updated']:,} | {s['unchanged']:,} | {s['max_sec']} |"
            )

        lines += [
            "",
            "### Per-File Detail",
            "| File | Target | Kind | Dur(s) | Parsed | Ins | Upd | Unch | Skip | Status |",
            "| ---- | ------ | ---- | ------ | ------ | --- | --- | ---- | ---- | ------ |",
        ]
        for f in r.get("files", []):
            fname = (f["file_name"] or "")[-60:]
            lines.append(
                f"| {fname} | {f['target_table']} | {f['kind']} | {f['duration_sec']} "
                f"| {f['parsed_rows'] or 0:,} | {f['inserted_rows'] or 0:,} "
                f"| {f['updated_rows'] or 0:,} | {f['unchanged_rows'] or 0:,} "
                f"| {f['skipped_rows'] or 0} | {f['status']} |"
            )

    with open("BENCHMARK_REPORT.md", "w") as fh:
        fh.write("\n".join(lines) + "\n")


def _write_daily_changes(all_results):
    lines = [
        "# LSEG Ingestion — Daily Change Matrix",
        f"\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "\n## Row-Level Change Counts (from lseg_file_audit)\n",
        "| Date | Inserted | Updated | Unchanged | Skipped | File INS ops | File UPD ops | File DEL ops |",
        "| ---- | -------- | ------- | --------- | ------- | ------------ | ------------ | ------------ |",
    ]
    for date, r in all_results.items():
        t = r.get("totals", {})
        lines.append(
            f"| {date} "
            f"| {(t.get('total_inserted') or 0):,} "
            f"| {(t.get('total_updated') or 0):,} "
            f"| {(t.get('total_unchanged') or 0):,} "
            f"| {(t.get('total_skipped') or 0):,} "
            f"| {(t.get('total_ins') or 0):,} "
            f"| {(t.get('total_upd') or 0):,} "
            f"| {(t.get('total_del') or 0):,} |"
        )

    lines += [
        "\n## Table Row Count Deltas (cumulative)\n",
        "| Date | lseg_orgs Δ | lseg_assets Δ | lseg_quotes Δ | lseg_pricing Δ | lseg_dss_bonds Δ |",
        "| ---- | ----------- | ------------- | ------------- | -------------- | ---------------- |",
        "|      | (total rows after day) | | | | |",
    ]
    for date, r in all_results.items():
        prev = r.get("prev_counts", {})
        curr = r.get("curr_counts", {})

        def delta(t):
            c, p = curr.get(t), prev.get(t)
            if c is None: return "N/A"
            d = (c or 0) - (p or 0)
            return f"{d:+,} → {c:,}"

        lines.append(
            f"| {date} | {delta('lseg_orgs')} | {delta('lseg_assets')} "
            f"| {delta('lseg_quotes')} | {delta('lseg_pricing')} | {delta('lseg_dss_bonds')} |"
        )

    with open("DAILY_CHANGES_REPORT.md", "w") as fh:
        fh.write("\n".join(lines) + "\n")


def _write_stability(all_results, stability_notes):
    total_jobs = len(all_results)
    completed = sum(1 for r in all_results.values() if r["status"] == "COMPLETED")
    failed = sum(1 for r in all_results.values() if r["status"] not in ("COMPLETED", "TRIGGER_FAILED"))
    total_files = sum((r.get("totals", {}).get("file_count") or 0) for r in all_results.values())
    total_failed_files = sum(len(r.get("failed_files", [])) for r in all_results.values())

    lines = [
        "# LSEG Ingestion — Stability Analysis",
        f"\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "\n## Run Overview\n",
        f"| Metric | Value |",
        f"| ------ | ----- |",
        f"| Date Range | {DATES[0]} → {DATES[-1]} |",
        f"| Total Jobs | {total_jobs} |",
        f"| Completed | {completed} |",
        f"| Failed/Stopped | {failed} |",
        f"| Total Files Processed | {total_files:,} |",
        f"| Files with Errors | {total_failed_files} |",
        f"| Overall Result | {'✓ ALL PASSED' if completed == total_jobs else '✗ SOME FAILED'} |",
        "",
        "## Per-Day Job Status\n",
        "| Date | Job ID | Status | Wall Time (s) | Success Files | Failed Files |",
        "| ---- | ------ | ------ | ------------- | ------------- | ------------ |",
    ]
    for date, r in all_results.items():
        t = r.get("totals", {})
        lines.append(
            f"| {date} | {r['job_id']} | {r['status']} | {r['wall_sec']:.0f} "
            f"| {t.get('success_files') or 0} | {t.get('failed_files') or 0} |"
        )

    if stability_notes:
        lines += ["\n## Issues & Exceptions\n"]
        for note in stability_notes:
            lines.append(f"- {note}")
    else:
        lines += ["\n## Issues & Exceptions\n", "No issues detected. All jobs completed cleanly.\n"]

    if total_failed_files > 0:
        lines += ["\n## Failed File Details\n",
                  "| Date | File | Target | Status | Error |",
                  "| ---- | ---- | ------ | ------ | ----- |"]
        for date, r in all_results.items():
            for ff in r.get("failed_files", []):
                err = (ff.get("error_message") or "")[:100].replace("|", "\\|")
                lines.append(
                    f"| {date} | {(ff['file_name'] or '')[-50:]} "
                    f"| {ff['target_table']} | {ff['status']} | {err} |"
                )

    with open("INGESTION_SUMMARY.md", "w") as fh:
        fh.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    run()
